### ISSUE TITLE
Recovery cannot mount NTFS devices

### ISSUE THREAD

**Issue by silentchild** [Ctapchuk/android_device_xiaomi_marble-OFRP#2]
Thank you for your work and report a problem. The current version cannot use OTG to mount USB devices.

**Comment by silentchild** [comment]
OrangeFox-R11.1_2-Beta-marble

**Comment by Ctapchuk** [comment]
> Thank you for your work and report a problem. The current version cannot use OTG to mount USB devices.

Thank you for report.
Looks like I can't reproduce same issue with my USB flash drive and USB mouse.
Can you send recovery.log file? Check /tmp/recovery.log in recovery or Internal Storage/Fox/logs/lastrecoverylog.log in booted system

**Comment by silentchild** [comment]
[lastrecoverylog.log](https://github.com/Ctapchuk/android_device_xiaomi_marble-OFRP/files/13808222/lastrecoverylog.log)

It probably has something to do with ntfs

**Comment by Ctapchuk** [comment]
> [lastrecoverylog.log](https://github.com/Ctapchuk/android_device_xiaomi_marble-OFRP/files/13808222/lastrecoverylog.log)
> 
> It probably has something to do with ntfs

Seems so.
```
I:Actual block device: '/dev/block/sdg1', current file system: 'ntfs'
I:Unable to mount '/usb_otg'
```
Recovery can only mount file systems supported by kernel (here we are dependent on current kernel in boot partition). Can you mount your OTG-storage in booted system? Maybe you need to change kernel with NTFS support, Melt kernel for example.

**Comment by silentchild** [comment]
Thank you for your answer. This is indeed the case. The kernel failed to mount. After replacing the kernel, it worked! Thank you again for your work~

**Comment by silentchild** [comment]
A log error was found,its not ntfs but vfat.The log says unable to mount but it mounted fine.
Nothing on the rec ui, it mounted fine and open any folder/file in it...
Just the log says it unable to mount
[recovery_20240102_092142.log.zip](https://github.com/Ctapchuk/android_device_xiaomi_marble-OFRP/files/13815965/recovery_20240102_092142.log.zip)

**Comment by Ctapchuk** [comment]
> A log error was found,its not ntfs but vfat.The log says unable to mount but it mounted fine. Nothing on the rec ui, it mounted fine and open any folder/file in it... Just the log says it unable to mount [recovery_20240102_092142.log.zip](https://github.com/Ctapchuk/android_device_xiaomi_marble-OFRP/files/13815965/recovery_20240102_092142.log.zip)

Looks like it works as it should, but I will check why these errors print in logs
