### ISSUE TITLE
Update the latest Magisk

### ISSUE THREAD

**Issue by silentchild** [Ctapchuk/android_device_xiaomi_marble-OFRP#3]
The built-in Magisk is an old version. I hope it can be updated to the new version simultaneously when updated.thank you for your work

**Comment by Ctapchuk** [comment]
I don't know what are you talking. Current OFRP includes Magisk 26.4 which is latest

**Comment by silentchild** [comment]
![c9b5ae7661f5530b8594a55a70d9bd0](https://github.com/Ctapchuk/android_device_xiaomi_marble-OFRP/assets/29771808/ca8dc08b-66af-4cab-a35c-5f2023fbc652)
![60c393b276e07dfdf3cd8d1097e549f](https://github.com/Ctapchuk/android_device_xiaomi_marble-OFRP/assets/29771808/81d4080c-caa2-4551-851b-e3bfd5d635d4)
![ae2d910ca9663bc977823d06192e92b](https://github.com/Ctapchuk/android_device_xiaomi_marble-OFRP/assets/29771808/96e55c9b-783d-4f0e-85c6-eac32eec44ee)
The current version is 26.3

**Comment by Ctapchuk** [comment]
Alright, you are right. For unknown for me reason, magisk was downgraded to 26.3 in latest build although I updated it to 26.4 in previous build. Magisk 26.4 will be in next build. Thanks for notice.
